// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5plF19DQPi5eT53WGqP-badMVcVm5NbY',
    appId: '1:915489835939:web:b759db00782f23949ca816',
    messagingSenderId: '915489835939',
    projectId: 'clutch-a2f49',
    authDomain: 'clutch-a2f49.firebaseapp.com',
    storageBucket: 'clutch-a2f49.appspot.com',
    measurementId: 'G-V2WXKR7B6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE72qmUBISfd4eQZDglxOxeuQppiKvsTg',
    appId: '1:915489835939:android:57b2882c9b1651fa9ca816',
    messagingSenderId: '915489835939',
    projectId: 'clutch-a2f49',
    storageBucket: 'clutch-a2f49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8D9m0zdzdjpazFdn1QlrgVrwQRbqNbfo',
    appId: '1:915489835939:ios:5da94fff20817d289ca816',
    messagingSenderId: '915489835939',
    projectId: 'clutch-a2f49',
    storageBucket: 'clutch-a2f49.appspot.com',
    iosClientId: '915489835939-236i902iq0ceppdnkghv88nikkdjjggo.apps.googleusercontent.com',
    iosBundleId: 'com.crixels.clutch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8D9m0zdzdjpazFdn1QlrgVrwQRbqNbfo',
    appId: '1:915489835939:ios:2de52a49b6cfc3ce9ca816',
    messagingSenderId: '915489835939',
    projectId: 'clutch-a2f49',
    storageBucket: 'clutch-a2f49.appspot.com',
    iosClientId: '915489835939-fpg021jrn2qr4eb6qkptmgj2kktq47j6.apps.googleusercontent.com',
    iosBundleId: 'com.example.clutch.RunnerTests',
  );
}
