List<String> lastMaintenanceList = [
  'Oil change',
  'Air filter replacement',
  'Spark plug replacement',
  'Brake pad replacement',
  'Tire rotation',
  'Wheel alignment',
  'Battery replacement',
  'Fluid top-up (coolant, brake fluid, etc.)',
  'Belts and hoses inspection',
  'Cabin air filter replacement',
  'Engine air filter replacement',
  'Fuel filter replacement',
  'Transmission fluid change',
  'Power steering fluid flush',
  'Throttle body cleaning',
  'Brake fluid flush',
  'Fuel system cleaning',
  'Wheel bearing inspection',
  'Suspension inspection',
  'Exhaust system inspection',
  'Ignition system inspection',
  'Timing belt replacement',
  'Radiator flush',
  'Wiper blade replacement',
  'Headlight bulb replacement',
  'Other',
  // Add more options
];
